#!/bin/bash

DATA_DIR=test_data/FEI_4_Viruses

src/ai_single_axis \
--gamma=10.0 \
--ctf-cutoff=2.5 \
--tiltangles-file=test_data/FEI_4_Viruses/tiltangles.txt \
--reco-params-file=test_data/FEI_4_Viruses/rec_params.cfg \
--mollifier=gaussian \
--invert-contrast \
--fft-padding=20 \
--verbose \
--output-file=test_data/FEI_4_Viruses/series2_rec_nonormalize.mrc \
test_data/FEI_4_Viruses/series2.mrc


#--normalize \
#--background=700,0,50,50 \
